
use test;
select * from emp_info;
SELECT * FROM emp_sal;

-----------QUESTION 1----------

--  CREATE A VIEW EMP_SAL_DETAILS TO GET EID NAME DOJ DEPT DESI SALARY AS BASIC. ALSO CALCULATE HRA (15% OF BASIC), PF (9% OF BASIC),NET(BASIC+HRA+PF)---

CREATE VIEW View_Emp_det as

select emp_info.EMP_ID,NAME,ADDR, DOJ,DEPT,DESIG, BASIC,BASIC*0.15 AS HRA, BASIC*0.09 AS PF,BASIC+BASIC*0.15+BASIC*0.09 AS NET_SAL
FROM emp_info
INNER JOIN emp_sal
ON emp_info.EMP_ID = emp_sal.EMP_ID;

--- drop view --
drop view View_Emp_det;


select * from View_emp_det;

-----------QUESTION 2 ----------
--CREATE A VIEW TO DISPLAY EID,NAME, DOJ, DESI, DEPT OF ALL THE MANAGERS JOINED IN 2019--

create view view_emp as
(select emp_info.EMP_ID,NAME,DOJ,DESIG,DEPT
FROM emp_info
INNER JOIN emp_sal
ON emp_info.EMP_ID = emp_sal.EMP_ID
WHERE DESIG = 'MGR' AND YEAR(DOJ) >= 1980);


SELECT * FROM view_emp;

DROP VIEW view_emp;


-----------QUESTION 3 ----------
--IN THE INVENTORY STRUCTURE GENERATE A VIEW BILL. IT SHOULD DISPLAY OID,ODATE,CNAME,ADDRESS,PHONE,PDESC, PRICE, OQTY, AMOUNT--

USE INVENTORY;

CREATE VIEW VIEW_BILL AS
SELECT ORDERS.OID,ODATE,CNAME,ADDRESS,PHONE,PDESC,PRICE,ODQTY,PRICE*ODQTY AS AMOUNT
FROM ORDERS
INNER JOIN CUST
ON ORDERS.CID = CUST.CID
INNER JOIN PRODUCT
ON ORDERS.PID = PRODUCT.PID;

SELECT* FROM VIEW_BILL;
